const SYNTHACTIONS = {
    SET_SYNTH: "SET_SYNTH",
    SET_VOLUME: "SET_VOLUME",
    SET_DELAY: "SET_DELAY",
    SET_DISTORTION: "SET_DISTORTION",
    SET_TREMOLO: "SET_TREMOLO",
    SET_BITCRUSHER: "SET_BITCRUSHER"
}

export default SYNTHACTIONS;