const SYNTHACTIONS = {
    SET_SYNTH: "SET_SYNTH",
    SET_VOLUME: "SET_VOLUME",
    SET_DELAY: "SET_DELAY",
    SET_WAH: "SET_WAH",
    SET_DISTORTION: "SET_DISTORTION",
    SET_TREMOLO: "SET_TREMOLO",
    SET_BITCRUSHER: "SET_BITCRUSHER",
    SET_ATTACK: "SET_ATTACK",
    SET_DECAY: "SET_DECAY",
    SET_SUSTAIN: "SET_SUSTAIN",
    SET_RELEASE: "SET_RELEASE",
    SET_LOW_EQ: "SET_LOW_EQ",
    SET_MID_EQ: "SET_MID_EQ",
    SET_HIGH_EQ: "SET_HIGH_EQ",
    SET_OCTAVE: "SET_OCTAVE"
}

export default SYNTHACTIONS;