const SYNTHACTIONS = {
    SET_SYNTH: "SET_SYNTH",
    SET_VOLUME: "SET_VOLUME",
    SET_DELAY: "SET_DELAY",
    SET_DISTORTION: "SET_DISTORTION",
    SET_TREMOLO: "SET_TREMOLO",
    SET_BITCRUSHER: "SET_BITCRUSHER",
    SET_ATTACK: "SET_ATTACK",
    SET_DECAY: "SET_DECAY",
    SET_SUSTAIN: "SET_SUSTAIN",
    SET_RELEASE: "SET_RELEASE"
}

export default SYNTHACTIONS;